name: Executar Código Automaticamente

on:
  schedule:
    - cron: '0 12 * * *'  # Executa todos os dias ao meio-dia UTC
  workflow_dispatch:  # Permite execução manual pelo GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest  # Servidor do GitHub roda no Linux
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Define a versão do Python

      - name: Instalar dependências
        run: pip install -r requirements.txt  # Se necessário

      - name: Executar código
        run: python testGit.py  # Substitua pelo seu script
